pipeline {
  options {
    buildDiscarder(logRotator(numToKeepStr: '5'))
    skipStagesAfterUnstable()
    disableConcurrentBuilds()
  }
  agent {
    kubernetes {
      inheritFrom 'c8y-hugo'
      defaultContainer 'default'
    }
  }
  environment {
    YUM_SRV = 'staging-resources.cumulocity.com'
    YUM_USR = 'hudson'
    YUM_DEST_DIR = '/var/www/staging-resources/releasenotes'
    HUGO_PARAMS = ""
  }
  stages {
    stage('Checkout') {
      steps {
        git branch: "develop", credentialsId: "jenkins-master", url:'git@github.com:SoftwareAG/c8y-releasenotes.git'
      }
    }
    stage('Build') {
      steps {
        sh '''bash --login
        python /previewScannerReleaseNotes.py
        echo \"Starting hugo with params ${HUGO_PARAMS}\"
        ls
        hugo ${HUGO_PARAMS}
        '''
      }
    }
    stage('Deploy') {
      steps {
        sshagent(['jenkins-master']) {
          sh '''bash --login
          pwd
          ls
          echo "rsync -e 'ssh -o StrictHostKeyChecking=no' -avh ./public/* ${YUM_USR}@${YUM_SRV}:${YUM_DEST_DIR} --delete"
          rsync -e 'ssh -o StrictHostKeyChecking=no' -avh ./public/* ${YUM_USR}@${YUM_SRV}:${YUM_DEST_DIR} --delete
          '''
        }
      }
    }
  }
}
